name: social-games-hoster

services:
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "32678:8080"                    
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - social-games-network

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: production
    ports:
      - "51144:51144" 
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080
      - NODE_ENV=production
      - DEV_SERVER_PORT=51144
    networks:
      - social-games-network

networks:
  social-games-network:
    driver: bridge