name: social-games-hoster

services:
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile.dev
    ports:
      - "8080:8080"                    
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RELOAD_ENABLED=true
    volumes:     
      - ./API:/src/API
      - nuget_packages:/root/.nuget/packages
    command: dotnet watch run --urls http://0.0.0.0:8080
    networks:
      - social-games-network
    depends_on:
      - db    

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081" 
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:8080
      - NODE_ENV=development
      - DEV_SERVER_PORT=8081
      - WATCHPACK_POLLING=true 
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=socialgamesdb;Username=dbuser;dbpassword
    volumes:
      - ./Web:/app 
      - /app/node_modules
    networks:
      - social-games-network

  db: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: socialgamesdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword # not a strong password, but this is only hosted locally.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - social-games-network

volumes:
  node_modules:
  nuget_packages:
  postgres_data:    
    
networks:
  social-games-network:
    driver: bridge