name: social-games-hoster

services:
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile.dev
    ports:
      - "8080:8080"                    
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RELOAD_ENABLED=true
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=socialgamesdb;Username=dbuser;Password=dbpassword
    volumes:         
      - ./API:/src/API
      - ./settings.ini:/src/API/settings.ini
      - nuget_packages:/root/.nuget/packages
    command: dotnet watch run --urls http://0.0.0.0:8080
    networks:
      - social-games-network
    depends_on:
      db: 
        condition: service_healthy    

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    environment:
      - VITE_API_URL=/api # This is the URL the web app will use to communicate with the API, but vite requires that environment variables are prefixed with VITE_.
      - NODE_ENV=development
      - DEV_SERVER_PORT=8081
      - WATCHPACK_POLLING=true
    volumes:
      - ./Web:/app 
      - /app/node_modules
    networks:
      - social-games-network

  db: 
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: socialgamesdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword # not a strong password, but this is only hosted locally.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - social-games-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d socialgamesdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - web
        - api
    networks:
        - social-games-network

  adminer: # PostgreSQL GUI
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB: socialgamesdb
      ADMINER_DEFAULT_USER: dbuser
      ADMINER_DEFAULT_PASSWORD: dbpassword
    networks:
      - social-games-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  node_modules:
  nuget_packages:
  postgres_data:    
    
networks:
  social-games-network:
    driver: bridge