# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS develop

WORKDIR /src/API

COPY ["API/API.csproj", "./"]

# Fetch all project dependencies.
RUN dotnet restore "./API.csproj"

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]