// <auto-generated />
using System;
using System.Net;
using API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.DataAccess.Migrations
{
    [DbContext(typeof(APIDatabaseContext))]
    [Migration("20260406111441_UseChatIsAdminFlag")]
    partial class UseChatIsAdminFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Participate in daily voting to lynch a suspect.",
                            Name = "Vote",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can defend themselves against night attacks.",
                            Name = "Defense",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Choose one player to protect from death each night.",
                            Name = "Heal",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Choose one player to investigate each night and learn their role category.",
                            Name = "Investigate",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Choose one player to kill each night. Limited uses.",
                            Name = "Shoot",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Execute the Mafia's chosen target at night.",
                            Name = "Mafia Kill",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Choose the Mafia's nightly target. Appears as Townie to investigators.",
                            Name = "Organize Kill",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "If lynched, you will kill one player who voted for you that night.",
                            Name = "Trick",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Win if your assigned target is lynched. You are immune to night kills until your target dies.",
                            Name = "Target Elimination",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 100,
                            Description = "Request an additional card to increase hand value.",
                            Name = "Hit",
                            RulesetId = 2
                        },
                        new
                        {
                            Id = 101,
                            Description = "Keep current hand and end turn.",
                            Name = "Stand",
                            RulesetId = 2
                        },
                        new
                        {
                            Id = 102,
                            Description = "Double the initial bet and receive one final card.",
                            Name = "Double Down",
                            RulesetId = 2
                        },
                        new
                        {
                            Id = 103,
                            Description = "If dealt a pair, split into two separate hands.",
                            Name = "Split",
                            RulesetId = 2
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.ChatChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("ChatChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Name = "Global"
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.ChatChannelMembership", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChatChannelMembership");
                });

            modelBuilder.Entity("API.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChannelId", "SentAt")
                        .HasDatabaseName("IX_ChatMessage_Channel_Time");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("API.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Alice Townie",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "John Doctor",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Emily Investigator",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Michael Vigilante",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 5,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Sarah Mafioso",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 6,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Jessica Godfather",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 7,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "David Jester",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 8,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Ashley Executioner",
                            RoleId = 8
                        },
                        new
                        {
                            Id = 9,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Matthew Townie",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Amanda Doctor",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Joshua Investigator",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Jennifer Vigilante",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 13,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Daniel Mafioso",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 14,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Elizabeth Godfather",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 15,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "James Jester",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 16,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Charlie Executioner",
                            RoleId = 8
                        },
                        new
                        {
                            Id = 17,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Kyle Townie",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Bob Doctor",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Megan Investigator",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            GameId = 1,
                            IsEliminated = false,
                            Name = "Laura Vigilante",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A regular citizen of the town. Your goal is to eliminate all threats.",
                            Name = "Townie",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "You are a medical professional dedicated to saving lives.",
                            Name = "Doctor",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "You seek the truth and uncover secrets hidden in the town.",
                            Name = "Investigator",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "You take justice into your own hands, even if it means getting your hands dirty.",
                            Name = "Vigilante",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "A loyal member of the Mafia. You carry out the family's nightly kills.",
                            Name = "Mafioso",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "The cunning leader of the Mafia. You are immune to basic investigations.",
                            Name = "Godfather",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Your only goal is to be lynched by the town.",
                            Name = "Jester",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "You have a specific target you must get lynched to win.",
                            Name = "Executioner",
                            RulesetId = 1
                        },
                        new
                        {
                            Id = 100,
                            Description = "A participant in the game aiming to beat the dealer by achieving a hand value of 21 or less.",
                            Name = "Player",
                            RulesetId = 2
                        },
                        new
                        {
                            Id = 101,
                            Description = "The house representative who manages the game, deals cards, and plays against the players.",
                            Name = "Dealer",
                            RulesetId = 2
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.RoleKnowledge", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<int>("KnowledgeType")
                        .HasColumnType("integer");

                    b.HasKey("SourceId", "TargetId");

                    b.HasIndex("TargetId");

                    b.ToTable("RoleKnowledges");

                    b.HasData(
                        new
                        {
                            SourceId = 6,
                            TargetId = 5,
                            KnowledgeType = 100
                        },
                        new
                        {
                            SourceId = 5,
                            TargetId = 6,
                            KnowledgeType = 100
                        },
                        new
                        {
                            SourceId = 100,
                            TargetId = 100,
                            KnowledgeType = 100
                        },
                        new
                        {
                            SourceId = 100,
                            TargetId = 101,
                            KnowledgeType = 100
                        },
                        new
                        {
                            SourceId = 101,
                            TargetId = 100,
                            KnowledgeType = 100
                        },
                        new
                        {
                            SourceId = 101,
                            TargetId = 101,
                            KnowledgeType = 100
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.RoundPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId");

                    b.ToTable("RoundPhases");
                });

            modelBuilder.Entity("API.Domain.Entities.Ruleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Rulesets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Town members aim to find and eliminate all evil roles, while Mafia and Neutral roles have their own secret goals, often involving the elimination of Town members. The game alternates between night, where players use their unique abilities, and day, where they discuss information, share their 'wills', and vote to hang someone.",
                            Name = "Town of Salem"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Blackjack, also known as 21, is a popular card game where players aim to have a hand value as close to 21 as possible without exceeding it. Players compete against the dealer rather than each other. The game involves strategic decisions such as hitting, standing, doubling down, and splitting pairs.",
                            Name = "Blackjack"
                        });
                });

            modelBuilder.Entity("API.Domain.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentPhaseId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PhaseStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RoundStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPhaseId");

                    b.HasIndex("RulesetId");

                    b.ToTable("GameSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhaseStartedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RoundNumber = 0,
                            RoundStartedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RulesetId = 1,
                            Status = 100
                        });
                });

            modelBuilder.Entity("PlayerPlayer", b =>
                {
                    b.Property<int>("CanBeSeenById")
                        .HasColumnType("integer");

                    b.Property<int>("CanSeeId")
                        .HasColumnType("integer");

                    b.HasKey("CanBeSeenById", "CanSeeId");

                    b.HasIndex("CanSeeId");

                    b.ToTable("PlayerVisibility", (string)null);
                });

            modelBuilder.Entity("RoleAbilities", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("RoleAbilities");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            AbilityId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            AbilityId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            AbilityId = 6
                        },
                        new
                        {
                            RoleId = 5,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 5,
                            AbilityId = 7
                        },
                        new
                        {
                            RoleId = 6,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 6,
                            AbilityId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            AbilityId = 3
                        },
                        new
                        {
                            RoleId = 7,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 7,
                            AbilityId = 9
                        },
                        new
                        {
                            RoleId = 8,
                            AbilityId = 1
                        },
                        new
                        {
                            RoleId = 8,
                            AbilityId = 10
                        },
                        new
                        {
                            RoleId = 100,
                            AbilityId = 100
                        },
                        new
                        {
                            RoleId = 100,
                            AbilityId = 101
                        },
                        new
                        {
                            RoleId = 100,
                            AbilityId = 102
                        },
                        new
                        {
                            RoleId = 100,
                            AbilityId = 103
                        },
                        new
                        {
                            RoleId = 101,
                            AbilityId = 100
                        },
                        new
                        {
                            RoleId = 101,
                            AbilityId = 101
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.Ability", b =>
                {
                    b.HasOne("API.Domain.Entities.Ruleset", null)
                        .WithMany("Abilities")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.ChatChannel", b =>
                {
                    b.HasOne("API.Domain.Models.GameSession", null)
                        .WithMany("ChatChannels")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.ChatChannelMembership", b =>
                {
                    b.HasOne("API.Domain.Entities.ChatChannel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Player", "Player")
                        .WithMany("ChatChannelMemberships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("API.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("API.Domain.Entities.ChatChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Player", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("API.Domain.Entities.Player", b =>
                {
                    b.HasOne("API.Domain.Models.GameSession", "GameSession")
                        .WithMany("Participants")
                        .HasForeignKey("GameId");

                    b.HasOne("API.Domain.Models.GameSession", null)
                        .WithMany("Winners")
                        .HasForeignKey("GameSessionId");

                    b.HasOne("API.Domain.Entities.Role", "Role")
                        .WithMany("PlayersWithRole")
                        .HasForeignKey("RoleId");

                    b.Navigation("GameSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Domain.Entities.Role", b =>
                {
                    b.HasOne("API.Domain.Entities.Ruleset", null)
                        .WithMany("Roles")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.RoleKnowledge", b =>
                {
                    b.HasOne("API.Domain.Entities.Role", "Source")
                        .WithMany("KnowsAbout")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Role", "Target")
                        .WithMany("KnownBy")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("API.Domain.Entities.RoundPhase", b =>
                {
                    b.HasOne("API.Domain.Entities.Ruleset", null)
                        .WithMany("RoundPhases")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Models.GameSession", b =>
                {
                    b.HasOne("API.Domain.Entities.RoundPhase", "CurrentPhase")
                        .WithMany()
                        .HasForeignKey("CurrentPhaseId");

                    b.HasOne("API.Domain.Entities.Ruleset", "Ruleset")
                        .WithMany()
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPhase");

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("PlayerPlayer", b =>
                {
                    b.HasOne("API.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("CanBeSeenById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("CanSeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleAbilities", b =>
                {
                    b.HasOne("API.Domain.Entities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.ChatChannel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("API.Domain.Entities.Player", b =>
                {
                    b.Navigation("ChatChannelMemberships");
                });

            modelBuilder.Entity("API.Domain.Entities.Role", b =>
                {
                    b.Navigation("KnownBy");

                    b.Navigation("KnowsAbout");

                    b.Navigation("PlayersWithRole");
                });

            modelBuilder.Entity("API.Domain.Entities.Ruleset", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Roles");

                    b.Navigation("RoundPhases");
                });

            modelBuilder.Entity("API.Domain.Models.GameSession", b =>
                {
                    b.Navigation("ChatChannels");

                    b.Navigation("Participants");

                    b.Navigation("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
